USETEXTLINKS = 1;
STARTALLOPEN = 0;
HIGHLIGHT = 1;
HIGHLIGHT_BG = '#808080';
ICONPATH = 'images/skins/';
GLOBALTARGET = 'R';
foldersTree = gFld('', '','');
foldersTree.iconSrc = ICONPATH + 'tvblank.gif';
foldersTree.treeID = 'Tree1';

xWelcome = insFld(foldersTree, gFld('欢迎使用', 'Welcome'));
insDoc(xWelcome, gLnk('R', '功能介绍', 'introducation'));
insDoc(xWelcome, gLnk('R', '重要申明', 'declare'));
xinstalltion = insFld(foldersTree, gFld('如何安装', 'installtion'));
insDoc(xinstalltion, gLnk('R', '环境要求', 'requirements'));
insDoc(xinstalltion, gLnk('R', '安装步骤', 'install_steps'));
xfunctions = insFld(foldersTree, gFld('背景知识了解', 'functions'));
insDoc(xfunctions, gLnk('R', 'X-mer算法说明', 'function1'));
insDoc(xfunctions, gLnk('R', 'NSH的定义说明', 'function2'));
insDoc(xfunctions, gLnk('R', 'CE和LE的交叉反应', '3'));
insDoc(xfunctions, gLnk('R', 'Filtering功能', '6'));
x4 = insFld(foldersTree, gFld('功能介绍', '4'));
insDoc(x4, gLnk('R', '1-本地文件解析功能', '5'));
insDoc(x4, gLnk('R', '2-选择引物设计区域', '9'));
insDoc(x4, gLnk('R', '3-提交设计区域', '10'));
insDoc(x4, gLnk('R', '4-可用引物列表', '11'));
insDoc(x4, gLnk('R', '5-引物Filtering功能', '12'));
insDoc(x4, gLnk('R', '6-选定的CE与LE的Xmer', '13'));
insDoc(x4, gLnk('R', '7-生成加尾引物序列', '15'));
insDoc(foldersTree, gLnk('R', '常见问题', 'faq'));
insDoc(foldersTree, gLnk('R', '联系我们', 'contract'));
